#!/bin/sh -eu

cat <<EOF
window.API_DOMAIN="${API_DOMAIN}";
window.SENTRY_DSN="${SENTRY_DSN}";
window.SENTRY_ENVIRONMENT="${SENTRY_ENVIRONMENT}";
window.FIREBASE_CONFIG="${FIREBASE_CONFIG}";
window.FIREBASE_KEY_PUBLIC="${FIREBASE_KEY_PUBLIC}";
EOF
